server.port=8761
spring.application.name=eureka-server

# Do not register Eureka server itself as a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Dashboard
eureka.server.enable-self-preservation=false
spring.security.user.name=admin
spring.security.user.password=admin

# Zipkin Tracing
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
